apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis-deployment
  labels:
    app: flask-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: hotshot07/flask-redis:v1
        imagePullPolicy: Always
        command: [ "python" ]
        args: [ "app.py" ]
        ports:
        - containerPort: 5000

---
kind: Service
apiVersion: v1
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app 
  ports:
  # Default port used by the image
  - port: 5000